-- MySQL Script generated by MySQL Workbench
-- dim. 27 janv. 2019 19:04:06 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Author` ;

CREATE TABLE IF NOT EXISTS `library`.`Author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NOT NULL,
  `author_surname` VARCHAR(45) NOT NULL,
  `author_birthday` DATE NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `author_id_UNIQUE` ON `library`.`Author` (`author_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `library`.`Author_has_written_Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Author_has_written_Book` ;

CREATE TABLE IF NOT EXISTS `library`.`Author_has_written_Book` (
  `Author_author_id` INT NOT NULL,
  `Book_book_id` INT NOT NULL,
  PRIMARY KEY (`Author_author_id`, `Book_book_id`),
  CONSTRAINT `fk_Author_has_Book_Author`
    FOREIGN KEY (`Author_author_id`)
    REFERENCES `library`.`Author` (`author_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Author_has_Book_Book1`
    FOREIGN KEY (`Book_book_id`)
    REFERENCES `library`.`Book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Author_has_Book_Book1_idx` ON `library`.`Author_has_written_Book` (`Book_book_id` ASC) VISIBLE;

CREATE INDEX `fk_Author_has_Book_Author_idx` ON `library`.`Author_has_written_Book` (`Author_author_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `library`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Book` ;

CREATE TABLE IF NOT EXISTS `library`.`Book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(45) NOT NULL,
  `book_date` DATE NOT NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `book_id_UNIQUE` ON `library`.`Book` (`book_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

